@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

participant "DataMapper" as A
database Database

-> A: getData
activate A

A -> Database: fetchData
activate Database

Database -> A: resultData
deactivate Database
@enduml