@startuml ER Diagram

entity Users {
    * id : UUID <<generated>>
    --
    * email : TEXT
    * name : TEXT
    * passwordHash : TEXT
    * type : TEXT
}

entity Subjects {
    * id : UUID <<generated>>
    --
    * name : TEXT
}

entity Exams {
    * id : UUID <<generated>>
    --
    * name : TEXT
    * subjectId : UUID <<FK>>
    publishDate : TIMESTAMP
    closeDate : TIMESTAMP
}

entity Questions {
    * id : UUID <<generated>>
    --
    * question : TEXT
    * type : TEXT
    * marks : INTEGER
    * examId : UUID <<FK>>
}

entity Answers {
    * id : UUID <<generated>>
    --
    * answer : TEXT
    * questionId : UUID <<FK>>
}

entity ExamSubmissions {
    * id : UUID <<generated>>
    --
    * userId : UUID <<FK>>
    * examId : UUID <<FK>>
    * marks : INTEGER
}

entity QuestionSubmissions {
    * id : UUID <<generated>>
    --
    * answer : TEXT
    * examSubmissionId : UUID <<FK>>
    * questionId : UUID <<FK>>
}

entity InstructorSubjects {
    * id : UUID <<generated>>
    --
    * userId : UUID <<FK>>
    * subjectId : UUID <<FK>>
}

entity StudentSubjects {
    * id : UUID <<generated>>
    --
    * userId : UUID <<FK>>
    * subjectId : UUID <<FK>>
}

Subjects ||--o{ Exams
Exams ||--|{ Questions
Users ||--o{ ExamSubmissions
Exams ||--o{ ExamSubmissions
ExamSubmissions ||--o{ QuestionSubmissions
Questions ||--o{ QuestionSubmissions
Questions ||--o{ Answers

Users ||--o{ InstructorSubjects
Users ||--o{ StudentSubjects

Subjects ||-|{ InstructorSubjects
Subjects ||-|{ StudentSubjects

@enduml
