@startuml Use Case Diagram

left to right direction

actor Student
actor Administrator
actor Instructor

package System {
    usecase "Submit exam" as UC01
    usecase "Create exam" as UC02
    usecase "Mark exams" as UC03
    usecase "Publish exam results" as UC04
    usecase "Add subjects" as UC05
    usecase "View all subjects" as UC06
    usecase "Delete exam" as UC07
    usecase "Edit exam" as UC08
    usecase "Close exam" as UC09
    usecase "View published exams" as UC10
    usecase "Answer question" as UC11
    usecase "View subjects" as UC12
    usecase "Publish exam" as UC13
    usecase "View all exams" as UC14
    usecase "Create question" as UC15
}

Student --> UC01
Student --> UC10
Student --> UC11
Student --> UC12

Instructor --> UC02
Instructor --> UC03
Instructor --> UC04
Instructor --> UC07
Instructor --> UC08
Instructor --> UC09
Instructor --> UC13
Instructor --> UC14
Instructor --> UC15

Administrator --> UC05
Administrator --> UC06

@enduml
