@startuml Association Table

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 230
skinparam sequenceParticipant underline

participant "subjectMapper" as A
database Database

-> A: getSubjectsForInstructor(instructorId)
activate A

A -> Database: "SELECT * FROM subjects JOIN instructor_subjects ON subjects.id = instructor_subjects.subject_id WHERE instructor_subjects.user_id = 'instructorId'
activate Database

Database --> A: ResultSet
deactivate Database

<-- A : List<Subject>
deactivate Database

@enduml