@startuml Embedded Value

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 200
skinparam sequenceParticipant underline

participant "ExamMapper" as A
database Database as B

-> A: findById(examId)
activate A

A -> B: SELECT * FROM exams WHERE exam_id ='examId'
activate B

B --> A: ResultSet{..DateRange..}
deactivate B

 <-- A : Exam{..startTime,finishTime..}
deactivate A

@enduml