@startuml Foreign Key

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 190
skinparam sequenceParticipant underline

participant "ExamMapper" as A
database Database as B

-> A: createExam(name,description,startTime,finishTime,subjectId)
activate A

A -> B: INSERT INTO exams id,slug,name,description,start_time,finish_time,subject_id
activate B

deactivate B

<-- A : Exam
deactivate A

@enduml