@startuml Identity Field

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 150
skinparam sequenceParticipant underline

participant "subjectMapper" as A
database Database as B

-> A: createSubject(name,description,instructors,students)
activate A

A -> B: INSERT INTO subjects id, slug, name, description
activate B

B --> A: ResultSet
deactivate B

 <-- A : Subject
deactivate A

@enduml