@startuml Identity Field

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 140
skinparam sequenceParticipant underline

participant "subject" as B
participant "model" as C
participant "UUID" as D

-> B: <<create>>(name,description)
activate B 

B -> C: <<create>>()
activate C

C -> D:randomUUID()
activate D

D -> C: id
deactivate D
deactivate C
deactivate B

@enduml
