@startuml Identity Map

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 200
skinparam sequenceParticipant underline

participant "SubjectMapper" as A
database Database as B

-> A: findById(subjectId)
activate A

A -> B: SELECT * FROM subjects WHERE subject_id ='subjectId'
activate B

B --> A: ResultSet
deactivate B

<-- A : Subject
deactivate A

@enduml