@startuml Optimistic Concurrency

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 180
skinparam sequenceParticipant underline

participant "SubjectController" as A
participant "SubjectService" as B

-> A: updateSubject(subjectId, headers, dto)
activate A

A -> B: updateSubject(name, description, subjectId, eTag)
activate B

alt subject.hashCode() == eTag

    B --> A: Subject
    deactivate B

    <-- A: Subject
    deactivate A

else 

    B --> A: PreConditionFailedException
    deactivate B

    <-- A: HTTP 412
    deactivate A

end

@enduml
