@startuml Secure Pipe

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 180
skinparam sequenceParticipant underline

participant "Heroku" as A

-> A: https://swen90007-ekzameno.herokuapp.com/
activate A

<-- A: index.html
deactivate A

@enduml
