@startuml Single Table Inheritance

participant "UserMapper" as A
database Database as B
participant "AdministratorMapper" as C
participant "InstructorMapper" as D
participant "StudentMapper" as E

-> A: findByEmail(email)
activate A

A -> B: SELECT * FROM users where email = 'email'
activate B

B --> A: ResultSet
deactivate B

A -> A: load(rs)
activate A

alt type == "administrator"

    A -> C: load(rs)
    activate C

    C --> A: administrator
    deactivate C

else type == "instructor"

    A -> D: load(rs)
    activate D

    D --> A : instructor
    deactivate D

else type == "student"

    A -> E: load(rs)
    activate E

    E --> A: student
    deactivate E

end

A --> A: user

deactivate A

<-- A: user

deactivate A

@enduml